// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYZh38yYBIiEJNnW4SXxR3ln6bbuqySU',
    appId: '1:278153046142:android:c763543c33016e8999502f',
    messagingSenderId: '278153046142',
    projectId: 'reway-4d031',
    databaseURL: 'https://reway-4d031-default-rtdb.firebaseio.com',
    storageBucket: 'reway-4d031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnJS-g31dRLrYnIQLGXijqs4oSDpJCTik',
    appId: '1:278153046142:ios:7a4dd4a4a874698099502f',
    messagingSenderId: '278153046142',
    projectId: 'reway-4d031',
    databaseURL: 'https://reway-4d031-default-rtdb.firebaseio.com',
    storageBucket: 'reway-4d031.appspot.com',
    androidClientId: '278153046142-089rmt2proumdf65j5rr1j81j8jl8hqb.apps.googleusercontent.com',
    iosClientId: '278153046142-1du5hmqe75qk6adqg8ec4i4lac34km5l.apps.googleusercontent.com',
    iosBundleId: 'com.rewaytech.rewayrecyclers',
  );
}
